In [1]:
import numpy as np

In [22]:
first_arr = np.arange(12)
first_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
print(first_arr.mean())
print(first_arr.argmax())
print(first_arr.argmin())


5.5
11
0


In [23]:
choices = [12,13]
np.choose(first_arr,choices,mode="clip")



array([12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13])

In [26]:
sec_arr = np.zeros((2,2))

print(sec_arr)

[[0. 0.]
 [0. 0.]]


In [56]:
thrid_arr = np.ones((4,4))
print(thrid_arr)
four_arr = np.ones_like(first_arr, dtype=float)
print(four_arr)
print(four_arr.ndim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
1


In [47]:
np.linspace(0,230,10000)

array([0.00000000e+00, 2.30023002e-02, 4.60046005e-02, ...,
       2.29953995e+02, 2.29976998e+02, 2.30000000e+02])

In [55]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
king=np.random.random(20)
print(king)

[0.12613931 0.25979385 0.77028439 0.23744312 0.64364691 0.20282646
 0.81418829 0.07789633 0.0912438  0.22984602 0.77003689 0.43020828
 0.79637679 0.04842645 0.70152069 0.16710201 0.24612612 0.908735
 0.08014727 0.15363488]


In [63]:
np.sort(king)

array([0.04842645, 0.07789633, 0.08014727, 0.0912438 , 0.12613931,
       0.15363488, 0.16710201, 0.20282646, 0.22984602, 0.23744312,
       0.24612612, 0.25979385, 0.43020828, 0.64364691, 0.70152069,
       0.77003689, 0.77028439, 0.79637679, 0.81418829, 0.908735  ])

In [66]:
king.reshape(4,5)

array([[0.12613931, 0.25979385, 0.77028439, 0.23744312, 0.64364691],
       [0.20282646, 0.81418829, 0.07789633, 0.0912438 , 0.22984602],
       [0.77003689, 0.43020828, 0.79637679, 0.04842645, 0.70152069],
       [0.16710201, 0.24612612, 0.908735  , 0.08014727, 0.15363488]])

In [4]:
arr_1d = np.arange(0,12)
arr_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
arr_2d = np.array([arr_1d[:3],arr_1d[3:6],arr_1d[6:9],arr_1d[9:]])
arr_2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
arr_2d[1:,:2].shape

(3, 2)

In [18]:
arr_3d = np.array([arr_2d[:1],arr_1d[:3], arr_2d])
arr_3d

array([array([[0, 1, 2]]), array([0, 1, 2]),
       array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])], dtype=object)

In [23]:
list1 = [ i for i in range(4)]
list1

[0, 1, 2, 3]

In [46]:
arr_2d.shape


(4, 3)

In [60]:
arr_cond=arr_1d > 3
arr_cond = arr_cond.reshape(4,3)
print(arr_cond.shape,arr_2d.shape)



(4, 3) (4, 3)


(4, 3)

In [61]:
arr_2d[arr_cond]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [83]:
print(arr_2d.transpose(),'\n',arr_2d)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]] 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [84]:
arr_2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [94]:
arr_a = np.arange(8).reshape(2,4)

In [99]:
arr_b = np.arange(8,24,2).reshape(2,4)
print(arr_a,arr_b)

[[0 1 2 3]
 [4 5 6 7]] [[ 8 10 12 14]
 [16 18 20 22]]


In [100]:
arr_c = np.concatenate((arr_a,arr_b),axis=0)
arr_c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [102]:
arr_d= np.concatenate((arr_a,arr_b),axis=1)
arr_d

array([[ 0,  1,  2,  3,  8, 10, 12, 14],
       [ 4,  5,  6,  7, 16, 18, 20, 22]])

In [109]:
np.hsplit(arr_d,8)

[array([[0],
        [4]]), array([[1],
        [5]]), array([[2],
        [6]]), array([[3],
        [7]]), array([[ 8],
        [16]]), array([[10],
        [18]]), array([[12],
        [20]]), array([[14],
        [22]])]

In [112]:
np.vsplit(arr_c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8, 10, 12, 14]]),
 array([[16, 18, 20, 22]])]